### ISSUE TITLE
`micromamba-activate` can't get PATH

### ISSUE THREAD

**Issue by delnatan** [SqrtMinusOne/micromamba.el#1]
Hi! thanks for writing this package!

I'm running MacOS (Emacs 30) and when I run `micromamba-activate`, the prompts are fine and it detects all of my environments. But after I specify the environment name I got the `Something went wrong. Cannot get PATH` user error.

Running the `micromamba--parse-script-buffer` function returns the unpopulated list: `((path) (vars-unset) (vars-export) (scripts))`

I'm using micromamba 1.4.7. The output of running `micromamba shell activate imaging -s zsh` (my environment name is imaging):

```
PS1='(imaging) '
export PATH='/Users/delnatan/micromamba/envs/imaging/bin:/Users/delnatan/Apps/bin:/Users/delnatan/micromamba/condabin:/Users/delnatan/Apps/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin'
export CONDA_PREFIX='/Users/delnatan/micromamba/envs/imaging'
export CONDA_SHLVL='2'
export CONDA_DEFAULT_ENV='imaging'
export CONDA_PROMPT_MODIFIER='(imaging) '
export CONDA_PREFIX_1='/Users/delnatan/micromamba'
. "/Users/delnatan/micromamba/envs/imaging/etc/conda/activate.d/libarrow_activate.sh"
. "/Users/delnatan/micromamba/envs/imaging/etc/conda/activate.d/libglib_activate.sh"
. "/Users/delnatan/micromamba/envs/imaging/etc/conda/activate.d/libxml2_activate.sh"
```

Is this the root cause for the error?

**Comment by SqrtMinusOne** [comment]
Hmm, that's strange. Maybe something related to MacOS.

I've evaluated `(micromamba--parse-script-buffer)` in a buffer with your output and it seems to work as expected (just have to move the cursor to the top). Could you please evaluate and attach the results of:
- `(micromamba-envs)`
- `(micromamba--get-activation-parameters "imaging")`

And also:
- `micromamba shell -s bash activate imaging`
Because that's what the package runs.

**Comment by delnatan** [comment]
Ah ok, after I moved the cursor to the top, the list got populated with some parameters parsed from the buffer.

Running `(micromamba-envs)` gave me all of the environment names and its corresponding paths.

Running `(micromamba--get-activation-parameters "imaging")` gives the same empty lists : 
`((path) (vars-unset) (vars-export) (scripts))`.

Funny enough running `micromamba shell -s bash activate imaging` from `M-x shell-command` throws an error:
`The following argument was not expected: -s`

This is fixed by passing the `-s` argument at the end:
`micromamba shell activate imaging -s bash` gives:

```
warning  libmamba 'root_prefix' set with default value: /Users/delnatan/micromamba
PS1='(imaging) '
export PATH='/Users/delnatan/micromamba/envs/imaging/bin:/Users/delnatan/mambaforge/bin:/Users/delnatan/mambaforge/condabin:/Users/delnatan/Apps/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/Library/TeX/texbin:/usr/bin:/bin:/usr/sbin:/sbin'
export CONDA_PREFIX='/Users/delnatan/micromamba/envs/imaging'
export CONDA_SHLVL='1'
export CONDA_DEFAULT_ENV='imaging'
export CONDA_PROMPT_MODIFIER='(imaging) '
. "/Users/delnatan/micromamba/envs/imaging/etc/conda/activate.d/libarrow_activate.sh"
. "/Users/delnatan/micromamba/envs/imaging/etc/conda/activate.d/libglib_activate.sh"
. "/Users/delnatan/micromamba/envs/imaging/etc/conda/activate.d/libxml2_activate.sh"

```

I can't seem to find where in `micromamba.el` the command is formed before executed, if you point me to it I can work on a pull request or if it's simple enough that would be awesome if you can verify / check if this modification does not break the package on your end. I'm new to micromamba (and only use it on my MacOS) so I don't know if this is specific to MacOS or not.

Thanks!

**Comment by delnatan** [comment]
ah ok, I found it! I can confirm this works fine on my system with this modification (move the shell option, I used `-s zsh`) to the end.

**Comment by SqrtMinusOne** [comment]
Interesting. On my system it works fine either way.

Can you confirm that https://github.com/SqrtMinusOne/micromamba.el/commit/ce97237986668c31d9b023348f1ef16199276794 fixes the issue for you?

**Comment by delnatan** [comment]
yup, this fixes it! thanks! closing the issue
